/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.TableDiskon;
import javax.swing.JFrame;

/**
 *
 * @author lenovo
 */
public class DialogActionDiskon extends javax.swing.JDialog {
    private java.awt.Frame parent;
    private TableDiskon td;
    /**
     * Creates new form DialogTest
     */
    public DialogActionDiskon(java.awt.Frame parent, boolean modal, TableDiskon td) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.td = td;
    }
    
    private DialogActionDiskon(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlDas2 = new javax.swing.JLabel();
        jlBarang = new javax.swing.JLabel();
        jlDiskon = new javax.swing.JLabel();
        jlRiwayat = new javax.swing.JLabel();
        jlTransaksi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtDiskon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtBelanja = new javax.swing.JTextField();
        jbTambah = new javax.swing.JButton();
        jbUbah = new javax.swing.JButton();
        jtStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 600));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kasir.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aplikasi Kasir");

        jlDas2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlDas2.setForeground(new java.awt.Color(255, 255, 255));
        jlDas2.setText("Dashboard");
        jlDas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDas2MouseClicked(evt);
            }
        });

        jlBarang.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlBarang.setForeground(new java.awt.Color(255, 255, 255));
        jlBarang.setText("Barang");
        jlBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBarangMouseClicked(evt);
            }
        });

        jlDiskon.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlDiskon.setForeground(new java.awt.Color(255, 255, 255));
        jlDiskon.setText("Diskon");
        jlDiskon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDiskonMouseClicked(evt);
            }
        });

        jlRiwayat.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        jlRiwayat.setText("Riwayat");
        jlRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRiwayatMouseClicked(evt);
            }
        });

        jlTransaksi.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jlTransaksi.setText("Transaksi");
        jlTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTransaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRiwayat)
                            .addComponent(jlDiskon)
                            .addComponent(jlBarang)
                            .addComponent(jlDas2)
                            .addComponent(jlTransaksi))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(70, 70, 70)
                .addComponent(jlDas2)
                .addGap(25, 25, 25)
                .addComponent(jlBarang)
                .addGap(25, 25, 25)
                .addComponent(jlDiskon)
                .addGap(25, 25, 25)
                .addComponent(jlRiwayat)
                .addGap(25, 25, 25)
                .addComponent(jlTransaksi)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jlTest.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jlTest.setText("Diskon");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Id Diskon");

        jtId.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jtId.setPreferredSize(new java.awt.Dimension(300, 35));

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Diskon");

        jtDiskon.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jtDiskon.setPreferredSize(new java.awt.Dimension(300, 35));

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Status");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Min. Belanja");

        jtBelanja.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jtBelanja.setPreferredSize(new java.awt.Dimension(300, 35));

        jbTambah.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jbTambah.setText("Tambah Diskon");
        jbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTambahActionPerformed(evt);
            }
        });

        jbUbah.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jbUbah.setText("Ubah Diskon");
        jbUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbahActionPerformed(evt);
            }
        });

        jtStatus.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        jtStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum", "Sudah" }));
        jtStatus.setToolTipText("");
        jtStatus.setPreferredSize(new java.awt.Dimension(300, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTest)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jbUbah)
                                        .addGap(25, 25, 25)
                                        .addComponent(jbTambah))
                                    .addComponent(jtBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlTest)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbTambah)
                    .addComponent(jbUbah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTambahActionPerformed
        // TODO add your handling code here:
        TableDiskon td = new TableDiskon();
        td.setId_diskon(jtId.getText());
        td.setDiskon(Integer.parseInt(jtDiskon.getText()));
        td.setStatus(String.valueOf(jtStatus.getSelectedItem()));
        td.setMin_belanja(Integer.parseInt(jtBelanja.getText()));
        int hasil = td.tambah();
        if(hasil ==1){
            System.out.println("Berhasil");
        }else{
            System.out.println("Gagal");
        }
        this.dispose();
        
    }//GEN-LAST:event_jbTambahActionPerformed

    private void jbUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbahActionPerformed
        // TODO add your handling code here:
        String id = jtId.getText();
        int diskon = Integer.parseInt(jtDiskon.getText());
        String status = jtStatus.getSelectedItem().toString();
        int min = Integer.parseInt(jtBelanja.getText());
        int cek = td.ubah(id, diskon, status, min);
        if(cek ==1){
            System.out.println("Berhasil");
        }else{
            System.out.println("Gagal");
        }
        this.dispose();
        
        
    }//GEN-LAST:event_jbUbahActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jtId.setText(td.getId_diskon());
        jtDiskon.setText(String.valueOf(td.getDiskon()));
        jtStatus.setSelectedItem(td.getStatus());
        jtBelanja.setText(String.valueOf(td.getMin_belanja()));
    }//GEN-LAST:event_formWindowActivated

    private void jlDas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDas2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogDashboard dd = new DialogDashboard(parent, true);
        dd.setVisible(true);
    }//GEN-LAST:event_jlDas2MouseClicked

    private void jlBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBarangMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogBarang db = new DialogBarang(parent, true);
        db.setVisible(true);
    }//GEN-LAST:event_jlBarangMouseClicked

    private void jlDiskonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDiskonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogDiskon dd = new DialogDiskon(parent, true);
        dd.setVisible(true);
    }//GEN-LAST:event_jlDiskonMouseClicked

    private void jlRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRiwayatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogRiwayat dr = new DialogRiwayat(parent, true);
        dr.setVisible(true);
    }//GEN-LAST:event_jlRiwayatMouseClicked

    private void jlTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTransaksiMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogTransaksi dt = new DialogTransaksi(parent, true);
        dt.setVisible(true);
    }//GEN-LAST:event_jlTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogActionDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogActionDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogActionDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogActionDiskon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogActionDiskon dialog = new DialogActionDiskon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbTambah;
    private javax.swing.JButton jbUbah;
    private javax.swing.JLabel jlBarang;
    private javax.swing.JLabel jlDas;
    private javax.swing.JLabel jlDas1;
    private javax.swing.JLabel jlDas2;
    private javax.swing.JLabel jlDiskon;
    private javax.swing.JLabel jlRiwayat;
    public static final javax.swing.JLabel jlTest = new javax.swing.JLabel();
    private javax.swing.JLabel jlTransaksi;
    private javax.swing.JTextField jtBelanja;
    private javax.swing.JTextField jtDiskon;
    private javax.swing.JTextField jtId;
    private javax.swing.JComboBox<String> jtStatus;
    // End of variables declaration//GEN-END:variables
}
