/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.TableTransaksi1;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author lenovo
 */
public class DialogRiwayat extends javax.swing.JDialog {
    /**
     * Creates new form DialogTest
     */
    private java.awt.Frame parent;  
    public DialogRiwayat(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }
    
    public void tampil(){
        
        TableColumn kolom = null;
        TableTransaksi1 tt = new TableTransaksi1();
//        TableBarang tb = new TableBarang();

        String[] namaKolom = new String[] {"Id Riwayat", "Id Barang", "Qty", "Total Harga"};

        ArrayList<Object[]> listData = tt.getSemua();
        
        Object[][] data = new Object[1][7];
        
        data = listData.toArray(data);
        
        DefaultTableModel model = new DefaultTableModel(data, namaKolom){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        
        table.setModel(model);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlDas1 = new javax.swing.JLabel();
        jlBarang = new javax.swing.JLabel();
        jlDiskon = new javax.swing.JLabel();
        jlRiwayat = new javax.swing.JLabel();
        jlTransaksi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 600));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kasir.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aplikasi Kasir");

        jlDas1.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlDas1.setForeground(new java.awt.Color(255, 255, 255));
        jlDas1.setText("Dashboard");
        jlDas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDas1MouseClicked(evt);
            }
        });

        jlBarang.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlBarang.setForeground(new java.awt.Color(255, 255, 255));
        jlBarang.setText("Barang");
        jlBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlBarangMouseClicked(evt);
            }
        });

        jlDiskon.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlDiskon.setForeground(new java.awt.Color(255, 255, 255));
        jlDiskon.setText("Diskon");
        jlDiskon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlDiskonMouseClicked(evt);
            }
        });

        jlRiwayat.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        jlRiwayat.setText("Riwayat");
        jlRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlRiwayatMouseClicked(evt);
            }
        });

        jlTransaksi.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        jlTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jlTransaksi.setText("Transaksi");
        jlTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlTransaksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRiwayat)
                            .addComponent(jlDiskon)
                            .addComponent(jlBarang)
                            .addComponent(jlDas1)
                            .addComponent(jlTransaksi))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(70, 70, 70)
                .addComponent(jlDas1)
                .addGap(25, 25, 25)
                .addComponent(jlBarang)
                .addGap(25, 25, 25)
                .addComponent(jlDiskon)
                .addGap(25, 25, 25)
                .addComponent(jlRiwayat)
                .addGap(25, 25, 25)
                .addComponent(jlTransaksi)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 1, 36)); // NOI18N
        jLabel2.setText("Riwayat");

        table.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setMinimumSize(new java.awt.Dimension(300, 70));
        table.setPreferredSize(new java.awt.Dimension(300, 70));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_formWindowActivated

    private void jlDas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDas1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogDashboard dd = new DialogDashboard(parent, true);
        dd.setVisible(true);
    }//GEN-LAST:event_jlDas1MouseClicked

    private void jlBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlBarangMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogBarang db = new DialogBarang(parent, true);
        db.setVisible(true);
    }//GEN-LAST:event_jlBarangMouseClicked

    private void jlDiskonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlDiskonMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogDiskon dd = new DialogDiskon(parent, true);
        dd.setVisible(true);
    }//GEN-LAST:event_jlDiskonMouseClicked

    private void jlRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlRiwayatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogRiwayat dr = new DialogRiwayat(parent, true);
        dr.setVisible(true);
    }//GEN-LAST:event_jlRiwayatMouseClicked

    private void jlTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlTransaksiMouseClicked
        // TODO add your handling code here:
        this.dispose();
        DialogTransaksi dt = new DialogTransaksi(parent, true);
        dt.setVisible(true);
    }//GEN-LAST:event_jlTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogRiwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogRiwayat dialog = new DialogRiwayat(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlBarang;
    private javax.swing.JLabel jlDas;
    private javax.swing.JLabel jlDas1;
    private javax.swing.JLabel jlDiskon;
    private javax.swing.JLabel jlRiwayat;
    private javax.swing.JLabel jlTransaksi;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
