/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

//import TestKode.*;
import Backend.TableRiwayat;
import Backend.TableTransaksi;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author lenovo
 */
public class DialogTransaksi extends javax.swing.JDialog {
    private java.awt.Frame parent;
    /**
     * Creates new form DialogTambah2
     */
    public DialogTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }
    
    public void jumTotal(){
        TableRiwayat ran = new TableRiwayat();
        ran.setRiwayat(tfRiwayat.getText());
        String KodeBrg = ran.getRiwayat();
        ran.jumHarga(KodeBrg);
        System.out.println("Total : "+KodeBrg);
        System.out.println("Total : "+ran.getBanyak());
        iTotal.setText(String.valueOf("Rp. "+ran.getBanyak()));
        tfSubTotal.setText(String.valueOf(ran.getBanyak()));
        tfTotalHarga.setText(String.valueOf(ran.getBanyak()));
    }
    
    public void tampilBarang(String field){    
        TableColumn kolom = null;
        TableRiwayat ran = new TableRiwayat();
        ran.setRiwayat(tfRiwayat.getText());
        String KodeBrg = ran.getRiwayat();

//        String[] namaKolom = new String[] {"Kode Barang", "Nama Barang", "Harga", "Stok"};
        String[] namaKolom = new String[] {"Riwayat", "Kode Barang", "Nama Barang", "Harga", "Stok", "Qty", "Total Harga"};

        ArrayList<Object[]> listData = ran.getSemua(KodeBrg, field);
        
        Object[][] data = new Object[1][7];
        
        data = listData.toArray(data);
        
        DefaultTableModel model = new DefaultTableModel(data, namaKolom){
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        
        table.setModel(model);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNew = new javax.swing.JButton();
        jbKembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnTanggal = new javax.swing.JTextField();
        tfNamaKasir = new javax.swing.JTextField();
        tfRiwayat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tfKodeBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNamaBarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfStokBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfHargaBarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfQty = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        tfKodeDiskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfBelanja = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfKembali = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnCariDiskon = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        tfDiskon1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTotalHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jbNew.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jbNew.setText("Transaksi Baru");
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });

        jbKembali.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jbKembali.setText("Kembali");
        jbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKembaliActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(425, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(425, 100));

        btnTanggal.setEditable(false);

        tfNamaKasir.setEditable(false);
        tfNamaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaKasirActionPerformed(evt);
            }
        });

        tfRiwayat.setEditable(false);
        tfRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRiwayatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("No. Nota");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Kasir");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaKasir)
                            .addComponent(btnTanggal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        jPanel1.setPreferredSize(new java.awt.Dimension(425, 100));

        iTotal.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(iTotal)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(iTotal)
                .addGap(48, 48, 48))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 100));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Kode Barang");

        tfKodeBarang.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Nama Barang");

        tfNamaBarang.setEditable(false);
        tfNamaBarang.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Stok");

        tfStokBarang.setEditable(false);
        tfStokBarang.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Harga");

        tfHargaBarang.setEditable(false);
        tfHargaBarang.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah Barang");

        tfQty.setFont(new java.awt.Font("MS UI Gothic", 0, 11)); // NOI18N
        tfQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtyActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(204, 204, 204));
        btnTambah.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btnTambah.setText("Tambah Barang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnCari.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btnCari.setText("Cari Barang");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tfKodeDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeDiskonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Kode Diskon");

        tfBelanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBelanjaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel12.setText("Belanja");

        jLabel14.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Kembalian");

        tfKembali.setEditable(false);
        tfKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKembaliActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpan.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCariDiskon.setBackground(new java.awt.Color(204, 204, 204));
        btnCariDiskon.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        btnCariDiskon.setText("Cari Diskon");
        btnCariDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariDiskonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 100));

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub Total");

        tfSubTotal.setEditable(false);
        tfSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSubTotalActionPerformed(evt);
            }
        });

        tfDiskon1.setEditable(false);
        tfDiskon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiskon1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel13.setText("Diskon");

        jLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Total Harga");

        tfTotalHarga.setEditable(false);
        tfTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(tfDiskon1)
                    .addComponent(tfTotalHarga))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiskon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbNew)
                                .addGap(25, 25, 25)
                                .addComponent(jbKembali))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTambah))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel6))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(tfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(btnCari))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(tfKodeDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCariDiskon))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnSimpan))))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNew)
                    .addComponent(jbKembali))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfStokBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(btnCari)
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnHapus))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfKodeDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnCariDiskon))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBelanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKembaliActionPerformed
        this.dispose();
        DialogDashboard dd = new DialogDashboard(parent, true);
        dd.setVisible(true);
    }//GEN-LAST:event_jbKembaliActionPerformed

    private void tfQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtyActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        TableRiwayat ran = new TableRiwayat();
        ran.setRiwayat(tfRiwayat.getText());
        ran.setId_Barang(tfKodeBarang.getText());
        ran.setQty(Integer.parseInt(tfQty.getText()));

        ran.setHarga(Integer.parseInt(tfHargaBarang.getText()));
        int HargaBrg = ran.getHarga();
        int StokBrg = ran.getQty();
        int jum = HargaBrg * StokBrg;
        ran.setTotal_Harga(jum);
        System.out.println("Harga Barang : "+jum);

        int hasil = ran.tambah();
        tampilBarang("id_riwayat");
        if(hasil == 1){
            jumTotal();
            System.out.println("Berhasil menambah data");

            tfKodeBarang.setText("");
            tfNamaBarang.setText("");
            tfHargaBarang.setText("");
            tfStokBarang.setText("");
            tfQty.setText("");

            tfKodeBarang.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Gagal menambah barang");
            return;
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        TableRiwayat tr = new TableRiwayat();
        boolean ketemu = tr.cariBarang(tfKodeBarang.getText());

        if(ketemu){
            tfNamaBarang.setText(tr.getNama_Barang());
            tfStokBarang.setText(String.valueOf(tr.getstok()));
            tfHargaBarang.setText(String.valueOf(tr.getHarga()));
        }else{
            tfKodeBarang.setText("");
            tfKodeBarang.requestFocus();
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void tfKodeDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeDiskonActionPerformed

    }//GEN-LAST:event_tfKodeDiskonActionPerformed

    private void tfTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalHargaActionPerformed

    private void tfDiskon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiskon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiskon1ActionPerformed

    private void tfSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSubTotalActionPerformed

    private void tfBelanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBelanjaActionPerformed
                String total = tfTotalHarga.getText();
        int totalInt = Integer.parseInt(total);
        String bayar = tfBelanja.getText();
        int bayarInt = Integer.parseInt(bayar);
        if(totalInt > bayarInt){
            tfKembali.setText("");
            JOptionPane.showMessageDialog(this, "Uang anda kurang!!");
            return;
        }else{
            int hitung = bayarInt - totalInt;
            tfKembali.setText(String.valueOf(hitung));
            System.out.println("Hasil : "+hitung);
            btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_tfBelanjaActionPerformed

    private void tfKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        TableRiwayat ran = new TableRiwayat();
        
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();        
        
        String diskon = tfKodeDiskon.getText();
        
        if(diskon.isEmpty()){
            ran.setRiwayat(tfRiwayat.getText());
            ran.setId_Kasir(tfNamaKasir.getText());
            ran.setWaktu(dtf.format(now));
        
            ran.setId_Diskon("Tidak ada!!");
            
            ran.setTotal_Harga(Integer.parseInt(tfTotalHarga.getText()));
            ran.setBayar(Integer.parseInt(tfBelanja.getText()));
            ran.setKembalian(Integer.parseInt(tfKembali.getText()));
            
            int hasil = ran.tambahTransaksi();
            
            if(hasil == 1){
                tfRiwayat.setText("");
                btnTanggal.setText("");
                tfKodeDiskon.setText("");
                tfSubTotal.setText("");
                tfDiskon1.setText("");
                tfTotalHarga.setText("");
                tfBelanja.setText("");
                tfKembali.setText("");
                iTotal.setText("");
                tampilBarang("0");

                jbNew.requestFocus();
                System.out.println("Berhasil ");
            }else{
                System.out.println("gagal ");
            }
        }else{
            ran.setRiwayat(tfRiwayat.getText());
            ran.setId_Kasir(tfNamaKasir.getText());
            ran.setWaktu(dtf.format(now));
        
            ran.setId_Diskon(tfKodeDiskon.getText());
            
            ran.setTotal_Harga(Integer.parseInt(tfTotalHarga.getText()));
            ran.setBayar(Integer.parseInt(tfBelanja.getText()));
            ran.setKembalian(Integer.parseInt(tfKembali.getText()));
            
            int hasil = ran.tambahTransaksi();
            if(hasil ==1){
                tfRiwayat.setText("");
                btnTanggal.setText("");
                tfKodeDiskon.setText("");
                tfSubTotal.setText("");
                tfDiskon1.setText("");
                tfTotalHarga.setText("");
                tfBelanja.setText("");
                tfKembali.setText("");
                iTotal.setText("");
                tampilBarang("0");

                jbNew.requestFocus();
                System.out.println("Berhasil ");
            }else{
                System.out.println("gagal ");
            }
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariDiskonActionPerformed
        TableRiwayat ran = new TableRiwayat();
        boolean ketemu = ran.cariDiskon(tfKodeDiskon.getText());
        String status = ran.getStatus();
        if(ketemu){
            System.out.println("Diskon "+status);
            if(status.equalsIgnoreCase("belum")){
                int min_belanja = ran.getMin_Belanja();
                int subTotal = Integer.parseInt(tfSubTotal.getText());

                if(min_belanja < subTotal){
                    tfDiskon1.setText(String.valueOf(ran.getDiskon()));

                    int diskon = ran.getDiskon();

                    ran.setRiwayat(tfRiwayat.getText());
                    String KodeBrg = ran.getRiwayat();
                    ran.jumHarga(KodeBrg);
                    int harga = ran.getBanyak();
                    int hitung = harga - diskon;
                    tfTotalHarga.setText(String.valueOf(hitung));
                    System.out.println("Total : "+hitung);
                    iTotal.setText(String.valueOf("Rp. "+hitung));
                    btnSimpan.requestFocus();
                }else{
                    tfKodeDiskon.setText("");
                    tfDiskon1.setText("");
                    tfKodeDiskon.requestFocus();
                    JOptionPane.showMessageDialog(this, "Untuk memakai Kode Diskon ini minimal belanja "+min_belanja);
                }
            }else{
                tfKodeDiskon.setText("");
                tfDiskon1.setText("");
                tfKodeDiskon.requestFocus();
                JOptionPane.showMessageDialog(this, "Kode Diskon sudah di pakai!!");
            }
            
            
        }else{
            tfKodeDiskon.setText("");
            tfKodeDiskon.requestFocus();
            System.out.println("Tidak ada diskon");
        }
    }//GEN-LAST:event_btnCariDiskonActionPerformed

    private void tfNamaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaKasirActionPerformed

    private void tfRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRiwayatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRiwayatActionPerformed

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        TableTransaksi tt = new TableTransaksi();
//        Memasukan data id
        tfRiwayat.setText(String.valueOf(tt.GodId()));
        
//        Masukan data waktu sekarang
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        btnTanggal.setText(dtf.format(now));
        
//        Memasukan nama user name yang login
        tfNamaKasir.setText(tt.cari());
    }//GEN-LAST:event_jbNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTransaksi dialog = new DialogTransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariDiskon;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField btnTanggal;
    private javax.swing.JLabel iTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbKembali;
    private javax.swing.JButton jbNew;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfBelanja;
    private javax.swing.JTextField tfDiskon1;
    private javax.swing.JTextField tfHargaBarang;
    private javax.swing.JTextField tfKembali;
    private javax.swing.JTextField tfKodeBarang;
    private javax.swing.JTextField tfKodeDiskon;
    private javax.swing.JTextField tfNamaBarang;
    private javax.swing.JTextField tfNamaKasir;
    private javax.swing.JTextField tfQty;
    private javax.swing.JTextField tfRiwayat;
    private javax.swing.JTextField tfStokBarang;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTotalHarga;
    // End of variables declaration//GEN-END:variables
}
